### ISSUE TITLE
Support for language and other parameters?

### ISSUE THREAD

**Issue by alarcia** [CrahunGit/RedsysTPV#1]
Hello! You did a very nice job with this package, but I have encoutered with the need to alter the language of the Redsys TPV. This is done with the "Ds_Merchant_ConsumerLanguage" parameter, which is optional. Could you please add support for this parameter? It wouldn't hurt to support all of them, actually.

Thank you very much!

**Comment by CrahunGit** [comment]
Thanks for your words but who made all the effort was the original creator of this library. It's easy to modify the source code to include every parameter you need. For your needs you can add the "Ds_Merchant_ConsumerLanguage" to PaymentRequest object and then use model binding in your razor view. Anyway, I will add this new parameter for you.

**Comment by CrahunGit** [comment]
The new package 1.0.3 is now on nuget. Try it and send comments if everything is working as expected. I will close this issue.

**Comment by alarcia** [comment]
Thank you very much! I actually downloaded the source and added the parameters, but couldn't figure out how to zip it and use it as a custom nuGet package.

**Comment by CrahunGit** [comment]
Don't worry, I've just uploaded a new version to nuget, it's 1.0.4. Just upgrade the package using the nuget package manager. Now it includes an enum called "Language" with the redsys available codes.
