### ISSUE TITLE
New system of PaymentMethods

### ISSUE THREAD

**Issue by christofergg** [CrahunGit/RedsysTPV#2]
Hi,
with recently changes from redsys they've added 1 extra parameter in the request method (DS_MERCHANT_PAYMETHODS) it's possible to modify it?

**Comment by CrahunGit** [comment]
Yes, I will investigate further to add it on next version. Thanks for your help.

**Comment by CrahunGit** [comment]
I've updated the library with this parameter. You can set it using:

```chsarp
 paymentRequest.Ds_Merchant_PayMethod = PaymentMethod.CreditCard;
```

I've no way to test it so you can check it in your own environment and comment.

**Comment by christofergg** [comment]
I will test it soon as possible and i’ll update this comment with the result

**Comment by nGestionAlbert** [comment]
Hola!

¿Cómo asigno BIZUM al Ds_Merchant_PayMethod?

Ds_Merchant_PayMethod = **"z"** (no es posible)

Gracias!
