### ISSUE TITLE
Ds_Merchant_PayMethod BIZUM

### ISSUE THREAD

**Issue by nGestionAlbert** [CrahunGit/RedsysTPV#3]
Hola!

¿Cómo asigno BIZUM al Ds_Merchant_PayMethod?

Ds_Merchant_PayMethod = "z" (no es posible)

Gracias!

**Comment by CrahunGit** [comment]
Es un enumerado, pero no contemplé bizum. Lo añado y subiré una nueva versión.

Tendrás que hacer 
Ds_Merchant_PayMethod = PaymentMethod.Bizum

**Comment by nGestionAlbert** [comment]
Muchas gracias, 
Lo probaré en cuanto esté disponible y te muestro el resultado de esta excelente y útil modificación.

**Comment by CrahunGit** [comment]
Acabo de subir una versión nueva. Habia un bug y el parametro que se mandaba no era correcto. Ya está funcionando. Cierro el issue.
