### ISSUE TITLE
Compatible with net standard 2.0 & net standard 2.1 & netcoreapp3.1

### ISSUE THREAD

**Issue by ProDInfo** [CrahunGit/RedsysTPV#6]
I would like to modify the project to create nuget package that can use on different platforms:
.Net Standard 2.1
.Net Standard 2.0
Net Core 3.1
Net Framework 4.8

Actually only work on .Net Standard 2.1 and not it's incompatible with asp.net core 3.1. I neeed on some project that I work.

I can't see nothing on this repository about creation nuget package.
How contribute to this change? I Create a pull request with the change on all projects with multitargeting?

Very thanls

**Comment by CrahunGit** [comment]
We just need to downgrade the redsys library to target netstandard 2,which is compatible with all of this types of projects and blazor. Anyway, aspnet core 3.1 it's totally compatible with netstandard 2.1. You can check the reference guide [here](https://docs.microsoft.com/es-es/dotnet/standard/net-standard). I've uploaded the new version to nugget. Check it out.

**Comment by ProDInfo** [comment]
Yes,
I don't search all the dependencies but normally for netcoreapp3.1 the dependencies it's not the same version of nuget packages.
I test with net standard 2.0

**Comment by CrahunGit** [comment]
Try it. My tests are working fine with the new package
