### ISSUE TITLE
Ds_Merchant_PayMethod integer, should be Alphanumeric!

### ISSUE THREAD

**Issue by psilva-bomsite** [CrahunGit/RedsysTPV#7]
According to documentation here:
https://pagosonline.redsys.es/parametros-entrada-salida.html#entradaTable
![image](https://user-images.githubusercontent.com/20442628/113153705-45f90d00-922f-11eb-9543-f0d72f0ca42e.png)

The parameter DS_MERCHANT_PAYMETHODS accepts 1 alphanumeric character, more specific only the letters Z, P, R, N, or C
But the library has a enumerable lists of integers at PaymentMethod
This results in failure creating payments with specific paymentMethods.

**Comment by CrahunGit** [comment]
Sorry for the delay. Is it working as expected?
